// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Stefan Stechert

#include "controlprototypes.h"

const Prototypes &getPrototypes()
{
    // Magic Order:
    // 'Multiline' prop of TextBox has to be before 'Text' or default
    // else bug at multilined text at loading after saving INI
    //
    // Expand for new controls or new props
    //   ControlType
    //       PropName, DefaultValue, flagsSetWrite, checkRule, description;
    static const QMap<QString, QList<PropInfo>> typeMap = {
        {"Window", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "Window", "W", "",
                    "Control type"},
                {"Geometry", "50,50,500,500", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:ClipboardChanged,Closed,Resized,KeyPressed",
                    "Events that can trigger notifications"},
                {"Text", "", "SW", "",
                    "Window title text"},
                {"Clipboard", "", "S", "",
                    "Text content of the system clipboard"},
                {"AboutHeading", "SouthWest", "SW", "Single:North,NorthEast,East,SouthEast,South,SouthWest,West,NorthWest",
                    "Position of '?'-About-icon in Window (Linux/Windows only)"},
                {"MessageBoxNow", "", "S", "",
                    "Opens a message box with the given text; always read as ''"},
                {"QuitNow", "False", "S", "Single:True,False",
                    "Immediately quits the GUI if True"},
                {"Icon", "", "SW", "",
                    "Path to an icon for the GUI window"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                }},
        {"Button", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "Button", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "Clicked", "SW", "Multi:Clicked",
                    "Events that can trigger notifications"},
                {"Text", "Button #TYPECOUNT#", "SW", "",
                    "Text displayed on the button"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"TextBox", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "TextBox", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:ReturnPressed",
                    "Events that can trigger notifications"},
                {"MultiLine", "False", "SW", "Single:True,False",
                    "Multi-line input enabled"},
                {"Text", "", "SW", "",
                    "Text content displayed"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"ListBox", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "ListBox", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:Clicked,DoubleClicked,SelectionChanged",
                    "Events that can trigger notifications"},
                {"EntireTexts", "", "SW", "",
                    "All list entries"},
                {"MultiSelect", "False", "SW", "Single:True,False",
                    "Multiple selection enabled"},
                {"Selected", "", "SW", "IndecesInRange",
                    "Indices of selected rows"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"}
                }},
        {"Label", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "Label", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Text", "Label #TYPECOUNT#", "SW", "",
                    "Text displayed on the label"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"OpenButton", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "OpenButton", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,40,50", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "Chosen", "SW", "Multi:Chosen",
                    "Events that can trigger notifications"},
                {"Text", "Choose the path/dir", "SW", "",
                    "Message shown in dialog on some operating systems"},
                {"Category", "Path", "SW", "Single:Path,Dir",
                    "Selection type: file path or directory"},
                {"Extensions", extensionDefault(), "SW", "",
                    "File extension filter for file selection"},
                {"Suggestion", "C:/Temp/", "SW", "",
                    "Default path suggested when dialog opens"},
                {"Path", "", "S", "",
                    "Last chosen file or directory path"},
                {"Icon", ":/open.png", "SW", "",
                    "Optional custom icon path for the button"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"SaveButton", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "SaveButton", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,40,50", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "Chosen", "SW", "Multi:Chosen",
                    "Events that can trigger notifications"},
                {"Text", "Choose the path/dir", "SW", "",
                    "Message shown in dialog on some operating systems"},
                {"Category", "Path", "SW", "Single:Path,Dir",
                    "Selection type: file path or directory"},
                {"Extensions", extensionDefault(), "SW", "",
                    "File extension filter for file selection"},
                {"Suggestion", "C:/Temp/", "SW", "",
                    "Default path suggested when dialog opens"},
                {"Path", "", "S", "",
                    "Last chosen file or directory path"},
                {"Icon", ":/save.png", "SW", "",
                    "Optional custom icon path for the button"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"ImageView", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "ImageView", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,100,100", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:ClickedAtPos",
                    "Events that can trigger notifications"},
                {"Image", ":/PixelRuler.png", "SW", "",
                    "Path to the image file"},
                {"Scaling", "AutoShrink", "SW", "Scaling",
                    "Scaling factor; use 'AutoShrink' to fit automatically or specify a float value"},
                {"Opacity", "1.0", "SW", "",
                    "Transparency level: 1.0 = opaque, 0.5 = semi-transparent"},
                {"Offsets", "0,0", "SW", "Int:U,U",
                    "Offset in pixels from upper-left corner: left, top"},
                {"Dimensions", "1000,1000", "", "",
                    "Image dimensions in pixels: width, height"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"CheckBox", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "CheckBox", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,100,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:StateChanged",
                    "Events that can trigger notifications"},
                {"Text", "CheckBox #TYPECOUNT#", "SW", "",
                    "Text label shown beside the checkbox"},
                {"State", "Checked", "SW", "Single:Checked,Unchecked",
                    "Checkbox state"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"DropArea", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "DropArea", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,70,70", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "Dropped", "SW", "Multi:Dropped",
                    "Events that can trigger notifications"},
                {"Text", "Drop here", "SW", "",
                    "Text displayed inside the drop area"},
                {"EntirePaths", "", "S", "",
                    "List of last dropped file paths"},
                {"DragStyle", "background-color: lightblue;" + dropStyleDefault(), "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Style", "background-color: darkgrey;" + dropStyleDefault(), "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"DropDown", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "DropDown", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:SelectionChanged",
                    "Events that can trigger notifications"},
                {"EntireTexts", "", "SW", "",
                    "All list entries"},
                {"Selected", "1", "SW", "IndecesInRange",
                    "Index of currently selected item"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"Slider", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "Slider", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,50,20", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Events", "", "SW", "Multi:Moved,Pressed,Released",
                    "Events that can trigger notifications"},
                {"Value", "42", "SW", "Int:S",
                    "Current numeric value between Min and Max"},
                {"Min", "0", "SW", "Int:S",
                    "Minimum selectable value"},
                {"Max", "100", "SW", "Int:S",
                    "Maximum selectable value"},
                {"Orientation", "Horizontal", "SW", "Single:Horizontal,Vertical",
                    "Orientation of the slider"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }},
        {"ProgressBar", {
                {"Name", "", "SW", "UniqueNColon",
                    "Unique identifier for the control"},
                {"Type", "ProgressBar", "W", "",
                    "Control type"},
                {"Geometry", "10,#YPOS#,80,32", "SW", "Int:U,U,U,U",
                    "Left, top, width, height"},
                {"Value", "42", "SW", "Int:U",
                    "Current value in percent"},
                {"Style", "", "SW", "",
                    "CSS-style appearance using Qt setStyleSheet"},
                {"Show", "Normal", "SW", "Single:Normal,Disabled,Invisible,ToBeDeleted",
                    "Visibility and interaction state"},
                {"ToolTip", "", "SW", "",
                    "Tooltip text shown when hovering the control"},
                }}
    };

    return typeMap;
}
